name: Deploy app-deteksi to Production (SSH Rsync)

on:
  push:
    branches:
      - master

jobs:
  production-deploy:
    name: 🚀 Deploy to cPanel
    runs-on: ubuntu-latest
    
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 🚀 Deploy via Rsync
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvO"
        SOURCE: "./"
        REMOTE_HOST: ${{ secrets.SSH_HOST }}
        REMOTE_USER: ${{ secrets.SSH_USERNAME }}
        REMOTE_PORT: ${{ secrets.SSH_PORT }}
        TARGET: "/home/uucdjd7c/deteksi-padi.ngekos.mikrosite.web.id" 
        EXCLUDE: "/.git/, /.github/, /db/, /referensi/, *.sql, /Zzz/, README.md"
